name: Publish Package to npmjs
on:
   workflow_dispatch:
      inputs:
         version:
           description: "version"
           required: true
           default: "prerelease"
         preid:
           description: "version preid"
           required: false
           default: "alpha"
#   push:
#     branches:
#       - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - name: "Run Test"
        run: |
         npm run test
         npm run test:compiler
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - name: change version
        run: npm version ${{ github.event.inputs.version }} --git-tag-version=false --preid=${{ github.event.inputs.preid }}
      - name: set version
        id: step0
        run: |
          version=$(node --eval="process.stdout.write(require('./package.json').version)")
          echo "release version is $version"
          echo "::set-output name=version::$version"
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: "${{ github.event.inputs.version }} release ${{ steps.step0.outputs.version }}"
          add: "package.json"
          tag: '${{ steps.step0.outputs.version }}'
        
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: '${{ steps.step0.outputs.version }}'
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


